### ISSUE TITLE
Create a new GitHub organization?

### ISSUE THREAD

**Issue by arfon** [mozilla/open_source_health#2]
:wave: @rjweiss, you beat me to the punch here!

I was about to email and suggest that we set up a new GitHub organization, e.g. `oss-health` for this work. What do you think?

**Comment by franniez** [comment]
@arfon Just to clarify, you mean a new GitHub org that is owned by neither GitHub nor Mozilla, that would live at github.com/oss-health?

**Comment by arfon** [comment]
> @arfon Just to clarify, you mean a new GitHub org that is owned by neither GitHub nor Mozilla, that would live at github.com/oss-health?

Yep, that's exactly the sort of thing.

**Comment by arfon** [comment]
@rjweiss - I went ahead and made a new organization here: https://github.com/oss-metrics . Lemme know what you think!

**Comment by rjweiss** [comment]
That's fine with me!  I'll deprecate this repo and migrate over to oss-health.
